- name: Copy and run PowerShell script on Windows servers
  hosts: all
  gather_facts: false

  tasks:
    - name: Copy PowerShell script to remote server
      ansible.builtin.win_copy:
        src: files/uptime_check.ps1
        dest: C:\Users\Administrator\Documents\uptime_check.ps1

    - name: Execute the copied PowerShell script
      ansible.builtin.win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "C:\Users\Administrator\Documents\uptime_check.ps1"
